/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopproject;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author PC
 */
public class File_Maneger extends javax.swing.JFrame {

    private JFileChooser FileChooser;

    /**
     * Creates new form
     */
    public File_Maneger() {
        initComponents();
        FileChooser = new JFileChooser();
        FileChooser.setCurrentDirectory(new File("D:\\File Maneger"));
        FileChooser.setFileFilter(new FileNameExtensionFilter("note", "txt", "png"));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NewFileButton = new javax.swing.JButton();
        OpenFileButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        NewFileButton.setBackground(new java.awt.Color(255, 255, 255));
        NewFileButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NewFileButton.setForeground(new java.awt.Color(0, 0, 0));
        NewFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/new-document.png"))); // NOI18N
        NewFileButton.setText("new file");
        NewFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFileButtonActionPerformed(evt);
            }
        });

        OpenFileButton.setBackground(new java.awt.Color(255, 255, 255));
        OpenFileButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        OpenFileButton.setForeground(new java.awt.Color(0, 0, 0));
        OpenFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/open-folder-with-document.png"))); // NOI18N
        OpenFileButton.setText("open file");
        OpenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileButtonActionPerformed(evt);
            }
        });

        LogOutButton.setBackground(new java.awt.Color(255, 255, 255));
        LogOutButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(0, 0, 0));
        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oopproject/logout.png"))); // NOI18N
        LogOutButton.setText("LogOut");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpenFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addComponent(NewFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(NewFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OpenFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NewFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFileButtonActionPerformed
        user d = new user();

        FileManeger u = new FileManeger();
        for (int i = 0; i < user.usersList.size(); i++) {
            System.out.println(user.usersList.get(i).toString());
        }
        String path = "D:\\File Maneger\\";

//        u.CreateFile(path);
        this.setVisible(false);
        new NoteScreen().setVisible(true);
    }//GEN-LAST:event_NewFileButtonActionPerformed

    private void OpenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileButtonActionPerformed
        int value = FileChooser.showOpenDialog(this);
        FileManeger fileManeger = new FileManeger();
        user u = fileManeger.CheckingSign();
        File selectedFile = FileChooser.getSelectedFile();
        if (value == JFileChooser.APPROVE_OPTION) {
            try {
                // Get the selected file
                
                
                BufferedReader reader = new BufferedReader(new FileReader(selectedFile));
                StringBuilder contentBuilder = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    contentBuilder.append(line).append("\n");
                }

                u.ContentText = contentBuilder.toString();
                int i = 0;
                while (!user.usersList.get(i).sign) {
                    i++;
                }
                user.usersList.remove(i);
                fileManeger.JSONserializing(u);
                reader.close();
            } catch (Exception ioe) {
                System.err.println("Failed to load file: " + ioe.getMessage());
            }
        } else {
            System.out.println("No file chosen or dialog closed.");
        }
        String name= selectedFile.getName().substring(0, selectedFile.getName().length()-4);
        this.setVisible(false);
        new NoteScreen(name,selectedFile.getPath()).setVisible(true);
        

    }//GEN-LAST:event_OpenFileButtonActionPerformed
    private String encodeImageToBase64(BufferedImage img) {
        try (ByteArrayOutputStream boss = new ByteArrayOutputStream()) {
            ImageIO.write(img, "png", boss);
            byte[] bytes = boss.toByteArray();
            System.out.println(bytes.toString());
            return Base64.getEncoder().encodeToString(bytes);
        } catch (IOException ex) {
            ex.printStackTrace();
            return null;
        }
    }


    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
       int i=0;
          while (!user.usersList.get(i).sign){
          i++;
          }  
          user.usersList.get(i).sign=false;
          this.setVisible(false);
          new LogIn_Screen().setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(File_Maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(File_Maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(File_Maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(File_Maneger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new File_Maneger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton NewFileButton;
    private javax.swing.JButton OpenFileButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
